load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test",
    srcs = ["main.cpp"],
    deps = [
        "@folly//folly:folly",
    ],
)

test_suite(
    name = "tests",
    tests = [
        "@folly//folly/algorithm/simd/detail/test:simd_any_of_test",
        "@folly//folly/algorithm/simd/detail/test:simd_for_each_test",
        "@folly//folly/algorithm/simd/detail/test:traits_test",
        "@folly//folly/algorithm/simd/detail/test:unroll_utils_test",
        "@folly//folly/algorithm/simd/test:contains_test",
        "@folly//folly/algorithm/simd/test:find_first_of_test",
        "@folly//folly/algorithm/simd/test:find_fixed_test",
        "@folly//folly/algorithm/simd/test:movemask_test",
        "@folly//folly/algorithm/test:binary_heap_test",
        "@folly//folly/algorithm/test:stable_radix_sort_benchmark",
        "@folly//folly/algorithm/test:stable_radix_sort_test",
        "@folly//folly/channels/detail/test:atomic_queue_test",
        "@folly//folly/channels/detail/test:pointer_variant_test",
        "@folly//folly/channels/test:channel_processor_test",
        "@folly//folly/channels/test:channel_test",
        "@folly//folly/channels/test:fanout_channel_test",
        "@folly//folly/channels/test:fanout_sender_test",
        "@folly//folly/channels/test:max_concurrent_rate_limiter_test",
        "@folly//folly/channels/test:merge_channel_test",
        "@folly//folly/channels/test:merge_test",
        "@folly//folly/channels/test:multiplex_channel_test",
        "@folly//folly/channels/test:producer_test",
        "@folly//folly/channels/test:proxy_channel_test",
        "@folly//folly/channels/test:transform_test",
        "@folly//folly/chrono/test:clock_test",
        "@folly//folly/chrono/test:conv_test",
        "@folly//folly/codec/test:hex_test",
        "@folly//folly/codec/test:uuid_test",
        "@folly//folly/compression/elias_fano/test:bitvector_test",
        "@folly//folly/compression/elias_fano/test:eliasfano_test",
        "@folly//folly/compression/test:compression_test",
        "@folly//folly/compression/test:compression_context_pool_test",
        "@folly//folly/compression/test:instructions_test",
        "@folly//folly/compression/test:large_test",
        "@folly//folly/compression/test:quotient_multiset_test",
        "@folly//folly/compression/test:select64_test",
        "@folly//folly/concurrency/container/test:atomic_grow_array_test",
        "@folly//folly/concurrency/container/test:flat_combining_priority_queue_test",
        "@folly//folly/concurrency/container/test:lock_free_ring_buffer_test",
        "@folly//folly/concurrency/container/test:relaxed_concurrent_priority_queue_test",
        "@folly//folly/concurrency/container/test:single_writer_fixed_hash_map_test",
        "@folly//folly/concurrency/memory/test:atomic_read_mostly_main_ptr_test",
        "@folly//folly/concurrency/memory/test:primary_ptr_test",
        "@folly//folly/concurrency/memory/test:read_mostly_shared_ptr_stress_test",
        "@folly//folly/concurrency/memory/test:read_mostly_shared_ptr_test",
        "@folly//folly/concurrency/memory/test:ref_count_test",
        "@folly//folly/concurrency/test:atomic_shared_ptr_test",
        "@folly//folly/concurrency/test:cache_locality_test",
        "@folly//folly/concurrency/test:concurrent_hash_map_stress_test",
        "@folly//folly/concurrency/test:concurrent_hash_map_stress_test_no_simd",
        "@folly//folly/concurrency/test:concurrent_hash_map_test",
        "@folly//folly/concurrency/test:concurrent_hash_map_test_no_simd",
        "@folly//folly/concurrency/test:core_cached_shared_ptr_test",
        "@folly//folly/concurrency/test:dynamic_bounded_queue_test",
        "@folly//folly/concurrency/test:priority_unbounded_queue_set_test",
        "@folly//folly/concurrency/test:process_local_unique_id_test",
        "@folly//folly/concurrency/test:singleton_relaxed_counter_test",
        "@folly//folly/concurrency/test:thread_cached_synchronized_test",
        "@folly//folly/concurrency/test:unbounded_queue_test",
        "@folly//folly/container/detail/test:bool_wrapper_test",
        "@folly//folly/container/detail/test:f14_detail_test",
        "@folly//folly/container/test:array_test",
        "@folly//folly/container/test:bit_iterator_test",
        "@folly//folly/container/test:collection_util_test",
        "@folly//folly/container/test:dynamic_ring_queue_test",
        "@folly//folly/container/test:enumerate_test",
        "@folly//folly/container/test:evicting_cache_map_test",
        "@folly//folly/container/test:f14_asan_support_test",
        "@folly//folly/container/test:f14_fwd_test",
        "@folly//folly/container/test:f14_interprocess_test",
        "@folly//folly/container/test:f14_map-test",
        "@folly//folly/container/test:f14_map_fallback_test",
        "@folly//folly/container/test:f14_map_test",
        "@folly//folly/container/test:f14_policy_test",
        "@folly//folly/container/test:f14_set-test",
        "@folly//folly/container/test:f14_set_fallback_test",
        "@folly//folly/container/test:f14_set_test",
        "@folly//folly/container/test:fbvector_test",
        "@folly//folly/container/test:fixed_capacity_ring_queue_test",
        "@folly//folly/container/test:foreach_test",
        "@folly//folly/container/test:heap_vector_types_test",
        "@folly//folly/container/test:heterogeneous_access_test",
        "@folly//folly/container/test:intrusive_heap_test",
        "@folly//folly/container/test:irange_test",
        "@folly//folly/container/test:iterator_test",
        "@folly//folly/container/test:map_util_test",
        "@folly//folly/container/test:merge_test",
        "@folly//folly/container/test:range_traits_test",
        "@folly//folly/container/test:regex_match_cache_test",
        "@folly//folly/container/test:reserve_test",
        "@folly//folly/container/test:small_vector_test",
        "@folly//folly/container/test:sorted_vector_types_test",
        "@folly//folly/container/test:span_test",
        "@folly//folly/container/test:sparse_byte_set_test",
        "@folly//folly/container/test:std_bitset_test",
        "@folly//folly/container/test:tape_test",
        "@folly//folly/container/test:util_test",
        "@folly//folly/container/test:vector_bool_test",
        "@folly//folly/container/test:weighted_evicting_cache_map_test",
        "@folly//folly/coro/detail/test:pick_task_wrapper_test",
        "@folly//folly/coro/safe/detail/test:bind_async_closure_test",
        "@folly//folly/coro/safe/detail/test:define_movable_deep_const_lref_copyable_test",
        "@folly//folly/coro/safe/test:async_closure_test",
        "@folly//folly/coro/safe/test:captures_test",
        "@folly//folly/coro/safe/test:now_task_test",
        "@folly//folly/coro/safe/test:safe_task_test",
        "@folly//folly/coro/test:PromiseTest",
        "@folly//folly/coro/test:RustAdaptorsTest",
        "@folly//folly/coro/test:async_generator_test",
        "@folly//folly/coro/test:async_stack_test",
        "@folly//folly/coro/test:coro_test",
        "@folly//folly/coro/test:coroutine_test",
        "@folly//folly/coro/test:error_test",
        "@folly//folly/coro/test:generator_test",
        "@folly//folly/coro/test:gmock_helpers_test",
        "@folly//folly/coro/test:gtest_helpers_test",
        "@folly//folly/coro/test:request_context_test",
        "@folly//folly/coro/test:retry_test",
        "@folly//folly/coro/test:serial_queue_runner_test",
        "@folly//folly/coro/test:shared_promise_test",
        "@folly//folly/coro/test:sleep_test",
        "@folly//folly/coro/test:suspended_stack_test",
        "@folly//folly/coro/test:synchronized_test",
        "@folly//folly/coro/test:task_wrapper_test",
        "@folly//folly/coro/test:value_or_error_test",
        "@folly//folly/coro/test:value_or_fatal_test",
        "@folly//folly/coro/test:with_async_stack_test",
        "@folly//folly/crypto/test:blake2xb_test",
        "@folly//folly/crypto/test:lt_hash_test",
        "@folly//folly/crypto/test:lt_hash_test_avx2",
        "@folly//folly/crypto/test:lt_hash_test_sse2",
        "@folly//folly/debugging/exception_tracer/test:exception_counter_test",
        "@folly//folly/detail/base64_detail/test:base64_against_scalar_test",
        "@folly//folly/detail/test:async_trace_test",
        "@folly//folly/detail/test:benchmark_adaptive_test",
        "@folly//folly/detail/test:detail_typelist_test",
        "@folly//folly/detail/test:file_util_detail_test",
        "@folly//folly/detail/test:perf_scoped_test",
        "@folly//folly/detail/test:simple_simd_string_utils_test",
        "@folly//folly/detail/test:split_string_simd_test",
        "@folly//folly/detail/test:static_singleton_manager_test",
        "@folly//folly/detail/test:thread_local_detail_test",
        "@folly//folly/detail/test:traponavx512_test_negative",
        "@folly//folly/detail/test:tuple_test",
        "@folly//folly/detail/test:unique_instance_test",
        "@folly//folly/executors/task_queue/test:PriorityLifoSemMPMCQueueTest",
        "@folly//folly/executors/task_queue/test:PriorityUnboundedBlockingQueueTest",
        "@folly//folly/executors/task_queue/test:UnboundedBlockingQueueTest",
        "@folly//folly/executors/task_queue/test:striped_priority_unbounded_blocking_queue_test",
        "@folly//folly/executors/test:AsyncTest",
        "@folly//folly/executors/test:CodelTest",
        "@folly//folly/executors/test:ExecutorWithPriorityTest",
        "@folly//folly/executors/test:FiberIOExecutorTest",
        "@folly//folly/executors/test:GlobalCPUExecutorTest",
        "@folly//folly/executors/test:GlobalExecutorAssignmentTest",
        "@folly//folly/executors/test:GlobalExecutorTest",
        "@folly//folly/executors/test:GlobalIOExecutorTest",
        "@folly//folly/executors/test:IOThreadPoolDeadlockDetectorObserverTest",
        "@folly//folly/executors/test:IOThreadPoolExecutorTest",
        "@folly//folly/executors/test:SequencedExecutorTest",
        "@folly//folly/executors/test:SerialExecutorTest",
        "@folly//folly/executors/test:StrandExecutorTest",
        "@folly//folly/executors/test:ThreadedExecutorTest",
        "@folly//folly/executors/test:TimedDrivableExecutorTest",
        "@folly//folly/executors/test:TimekeeperScheduledExecutorTest",
        "@folly//folly/executors/test:executor_test",
        "@folly//folly/executors/test:function_scheduler_test",
        "@folly//folly/executors/test:striped_edf_thread_pool_executor_test",
        "@folly//folly/executors/test:threaded_repeating_function_runner_test",
        "@folly//folly/external/farmhash/test:farmhash_test",
        "@folly//folly/fibers/async/test:async_test",
        "@folly//folly/fibers/test:batch_semaphore_test",
        "@folly//folly/fibers/test:fibers_test",
        "@folly//folly/fibers/test:semaphore_test",
        "@folly//folly/functional/test:apply_tuple_test",
        "@folly//folly/functional/test:invoke_test",
        "@folly//folly/functional/test:partial_test",
        "@folly//folly/functional/test:protocol_test",
        "@folly//folly/functional/test:traits_test",
        "@folly//folly/futures/test:barrier_test",
        "@folly//folly/futures/test:callback_lifetime_test",
        "@folly//folly/futures/test:cleanup_test",
        "@folly//folly/futures/test:collect_test",
        "@folly//folly/futures/test:context_test",
        "@folly//folly/futures/test:conversion_operator",
        "@folly//folly/futures/test:core_test",
        "@folly//folly/futures/test:ensure_test",
        "@folly//folly/futures/test:filter_test",
        "@folly//folly/futures/test:future_splitter_test",
        "@folly//folly/futures/test:future_test",
        "@folly//folly/futures/test:header_compile_test",
        "@folly//folly/futures/test:heap_timekeeper_test",
        "@folly//folly/futures/test:interrupt_test",
        "@folly//folly/futures/test:manual_timekeeper_test",
        "@folly//folly/futures/test:map_test",
        "@folly//folly/futures/test:non_copyable_lambda_test",
        "@folly//folly/futures/test:poll_test",
        "@folly//folly/futures/test:promise_test",
        "@folly//folly/futures/test:reduce_test",
        "@folly//folly/futures/test:retrying_test",
        "@folly//folly/futures/test:self_destruct_test",
        "@folly//folly/futures/test:semi_future_test",
        "@folly//folly/futures/test:shared_promise_test",
        "@folly//folly/futures/test:test_executor_test",
        "@folly//folly/futures/test:then_compile_test",
        "@folly//folly/futures/test:then_test",
        "@folly//folly/futures/test:thread_wheel_timekeeper_test",
        "@folly//folly/futures/test:timekeeper_test",
        "@folly//folly/futures/test:times_test",
        "@folly//folly/futures/test:unwrap_test",
        "@folly//folly/futures/test:via_test",
        "@folly//folly/futures/test:wait_test",
        "@folly//folly/futures/test:when_test",
        "@folly//folly/futures/test:while_do_test",
        "@folly//folly/futures/test:will_equal_test",
        "@folly//folly/futures/test:window_test",
        "@folly//folly/gen/test:base_test",
        "@folly//folly/gen/test:combine_test",
        "@folly//folly/gen/test:file_test",
        "@folly//folly/gen/test:istream_test",
        "@folly//folly/gen/test:parallel_map_test",
        "@folly//folly/gen/test:parallel_test",
        "@folly//folly/gen/test:string_test",
        "@folly//folly/hash/detail/test:random_seed_test",
        "@folly//folly/hash/test:checksum_test",
        "@folly//folly/hash/test:farm_hash_test",
        "@folly//folly/hash/test:fnv_hash_test",
        "@folly//folly/hash/test:hash_test",
        "@folly//folly/hash/test:hsieh_hash_test",
        "@folly//folly/hash/test:murmur_hash_test",
        "@folly//folly/hash/test:rapidhash_test",
        "@folly//folly/hash/test:spooky_hash_v1_test",
        "@folly//folly/hash/test:spooky_hash_v2_test",
        "@folly//folly/hash/test:std_compatible_hash_test",
        "@folly//folly/hash/test:traits_test",
        "@folly//folly/hash/test:unique_hash_key_test",
    ],
)
