load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test",
    srcs = ["main.cpp"],
    deps = [
        "@folly//folly:folly",
    ],
)

test_suite(
    name = "tests",
    tests = [
        "@folly//folly/algorithm/simd/detail/test:simd_any_of_test",
        "@folly//folly/algorithm/simd/detail/test:simd_for_each_test",
        "@folly//folly/algorithm/simd/detail/test:traits_test",
        "@folly//folly/algorithm/simd/detail/test:unroll_utils_test",
        "@folly//folly/algorithm/simd/test:contains_test",
        "@folly//folly/algorithm/simd/test:find_first_of_test",
        "@folly//folly/algorithm/simd/test:find_fixed_test",
        "@folly//folly/algorithm/simd/test:movemask_test",
        "@folly//folly/algorithm/test:binary_heap_test",
        "@folly//folly/algorithm/test:stable_radix_sort_benchmark",
        "@folly//folly/algorithm/test:stable_radix_sort_test",
        "@folly//folly/channels/detail/test:atomic_queue_test",
        "@folly//folly/channels/detail/test:pointer_variant_test",
        "@folly//folly/channels/test:channel_processor_test",
        "@folly//folly/channels/test:channel_test",
        "@folly//folly/channels/test:fanout_channel_test",
        "@folly//folly/channels/test:fanout_sender_test",
        "@folly//folly/channels/test:max_concurrent_rate_limiter_test",
        "@folly//folly/channels/test:merge_channel_test",
        "@folly//folly/channels/test:merge_test",
        "@folly//folly/channels/test:multiplex_channel_test",
        "@folly//folly/channels/test:producer_test",
        "@folly//folly/channels/test:proxy_channel_test",
        "@folly//folly/channels/test:transform_test",
        "@folly//folly/chrono/test:clock_test",
        "@folly//folly/chrono/test:conv_test",
        "@folly//folly/codec/test:hex_test",
        "@folly//folly/codec/test:uuid_test",
        "@folly//folly/compression/elias_fano/test:bitvector_test",
        "@folly//folly/compression/elias_fano/test:eliasfano_test",
        "@folly//folly/compression/test:compression_test",
        "@folly//folly/compression/test:compression_context_pool_test",
        "@folly//folly/compression/test:instructions_test",
        "@folly//folly/compression/test:large_test",
        "@folly//folly/compression/test:quotient_multiset_test",
        "@folly//folly/compression/test:select64_test",
    ],
)
