load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test",
    srcs = ["main.cpp"],
    deps = ["@mvfst//quic:constants"],
)

test_suite(
    name = "tests",
    tests = [
        "@mvfst//quic/api/test:IoBufQuicBatchTest",
        "@mvfst//quic/api/test:QuicBatchWriterTest",
        "@mvfst//quic/api/test:QuicPacketSchedulerTest",
        "@mvfst//quic/api/test:QuicSocketTest",
        "@mvfst//quic/api/test:QuicStreamAsyncTransportTest",
        "@mvfst//quic/api/test:QuicTransportBaseTest",
        "@mvfst//quic/api/test:QuicTransportFunctionsTest",
        "@mvfst//quic/api/test:QuicTransportTest",
        "@mvfst//quic/api/test:QuicTypedTransportTest",
        "@mvfst//quic/client/test:ClientStateMachineTest",
        "@mvfst//quic/client/test:QuicClientTransportLiteMigrationTest",
        "@mvfst//quic/client/test:QuicClientTransportLiteTest",
        "@mvfst//quic/client/test:QuicClientTransportTest",
        "@mvfst//quic/client/test:QuicConnectorTest",
        "@mvfst//quic/codec/test:DecodeTests",
        "@mvfst//quic/codec/test:DefaultConnectionIdAlgoTest",
        "@mvfst//quic/codec/test:EcnTruncationTest",
        "@mvfst//quic/codec/test:PacketNumberTest",
        "@mvfst//quic/codec/test:QuicConnectionIdTest",
        "@mvfst//quic/codec/test:QuicHeaderCodec",
        "@mvfst//quic/codec/test:QuicIntegerTest",
        "@mvfst//quic/codec/test:QuicPacketBuilderTest",
        "@mvfst//quic/codec/test:QuicPacketRebuilderTest",
        "@mvfst//quic/codec/test:QuicReadCodecTests",
        "@mvfst//quic/codec/test:QuicWriteCodecTests",
        "@mvfst//quic/codec/test:TypesTests",
        "@mvfst//quic/codec/test:server_connection_id_params_test",
        "@mvfst//quic/common/events/test:FollyQuicEventBaseTest",
        "@mvfst//quic/common/events/test:LibevQuicEventBaseTest",
        "@mvfst//quic/common/test:BufAccessorTest",
        "@mvfst//quic/common/test:BufUtilTest",
        "@mvfst//quic/common/test:ChainedByteRangeTest",
        "@mvfst//quic/common/test:CircularDequeTest",
        "@mvfst//quic/common/test:ContiguousCursorTest",
        "@mvfst//quic/common/test:IntervalSetTest",
        "@mvfst//quic/common/test:LinuxKernelVersionTest",
        "@mvfst//quic/common/test:QuicBufferTest",
        "@mvfst//quic/common/test:QuicRangeConversionTest",
        "@mvfst//quic/common/test:SocketUtilTest",
        "@mvfst//quic/common/test:StringUtilsTest",
        "@mvfst//quic/common/test:TimeUtilTest",
        "@mvfst//quic/common/test:TransportKnobsTest",
        "@mvfst//quic/common/test:TransportLooperTest",
        "@mvfst//quic/common/test:VariantTest",
        "@mvfst//quic/common/udpsocket/test:FollyQuicAsyncUDPSocketTest",
        "@mvfst//quic/common/udpsocket/test:LibevQuicAsyncUDPSocketTest",
        "@mvfst//quic/congestion_control/test:BandwidthTest",
        "@mvfst//quic/congestion_control/test:Bbr2GainValidationTest",
        "@mvfst//quic/congestion_control/test:Bbr2Test",
        "@mvfst//quic/congestion_control/test:BbrBandwidthSamplerTest",
        "@mvfst//quic/congestion_control/test:BbrRttSamplerTest",
        "@mvfst//quic/congestion_control/test:BbrTest",
        "@mvfst//quic/congestion_control/test:CongestionControlFunctionsTest",
        "@mvfst//quic/congestion_control/test:CopaTest",
        "@mvfst//quic/congestion_control/test:CubicStateTest",
        "@mvfst//quic/congestion_control/test:CubicTest",
        "@mvfst//quic/congestion_control/test:EcnL4sTrackerTest",
        "@mvfst//quic/congestion_control/test:NewRenoTest",
        "@mvfst//quic/congestion_control/test:PacerTest",
        "@mvfst//quic/congestion_control/test:SimulatedTBFTest",
        "@mvfst//quic/congestion_control/test:StaticCwndCongestionControllerTest",
        "@mvfst//quic/congestion_control/test:ThrottlingSignalProviderTest",
        "@mvfst//quic/datagram/test:DatagramFlowManagerTest",
        "@mvfst//quic/fizz/client/handshake/test:FizzClientExtensionsTest",
        "@mvfst//quic/fizz/client/handshake/test:fizz_client_handshake_test",
        "@mvfst//quic/fizz/client/test:QuicClientTransportTest",
        "@mvfst//quic/fizz/handshake/test:FizzCryptoFactoryTest",
        "@mvfst//quic/fizz/handshake/test:FizzPacketNumberCipherTest",
        "@mvfst//quic/fizz/handshake/test:FizzTransportParametersTest",
        "@mvfst//quic/flowcontrol/test:QuicFlowControlTest",
        "@mvfst//quic/handshake/test:TransportParametersTest",
        "@mvfst//quic/logging/test:QLoggerTest",
        "@mvfst//quic/loss/test:QuicLossFunctionsTest",
        "@mvfst//quic/observer/test:SocketObserverInterfaceTest",
        "@mvfst//quic/priority/test:http_priority_queue_test",
        "@mvfst//quic/priority/test:priority_queue_test",
        "@mvfst//quic/priority/test:round_robin_test",
        "@mvfst//quic/server/async_tran/test:QuicAsyncTransportServerTest",
        "@mvfst//quic/server/handshake/test:AppTokenTest",
        "@mvfst//quic/server/handshake/test:DefaultAppTokenValidatorTest",
        "@mvfst//quic/server/handshake/test:RetryTokenGeneratorTest",
        "@mvfst//quic/server/handshake/test:ServerHandshakeTest",
        "@mvfst//quic/server/handshake/test:ServerTransportParametersTest",
        "@mvfst//quic/server/handshake/test:StatelessResetGeneratorTest",
        "@mvfst//quic/server/test:QuicClientServerIntegrationTest",
        "@mvfst//quic/server/test:QuicServerTest",
        "@mvfst//quic/server/test:QuicServerTransportMigrationTest",
        "@mvfst//quic/server/test:QuicServerTransportTest",
        "@mvfst//quic/server/test:ServerStateMachineTest",
        "@mvfst//quic/server/test:SlidingWindowRateLimiterTest",
        "@mvfst//quic/state/stream/test:StreamStateFunctionsTest",
        "@mvfst//quic/state/stream/test:StreamStateMachineTest",
        "@mvfst//quic/state/test:AckHandlersTest",
        "@mvfst//quic/state/test:ClonedPacketIdentifierTest",
        "@mvfst//quic/state/test:EcnTruncationIntegrationTest",
        "@mvfst//quic/state/test:OutstandingPacketTest",
        "@mvfst//quic/state/test:QuicPacingFunctionsTest",
        "@mvfst//quic/state/test:QuicStateFunctionsTest",
        "@mvfst//quic/state/test:QuicStateMachineTest",
        "@mvfst//quic/state/test:QuicStreamFunctionsTest",
        "@mvfst//quic/state/test:QuicStreamManagerTest",
        "@mvfst//quic/state/test:TransportSettingsFunctionsTest",
        "@mvfst//quic/state/test:acked_packet_iterator_test",
        "@mvfst//quic/state/test:quic_path_manager_test",
        "@mvfst//quic/state/test:stream_data_test",
        "@mvfst//quic/xsk/test:PacketUtilsTest",
    ],
)
