load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test",
    srcs = ["main.cpp"],
    deps = ["@fizz"],
)

test_suite(
    name = "tests",
    tests = [
        "@fizz//fizz/backend/liboqs/test:oqs_key_exchange_test",
        "@fizz//fizz/backend/openssl/certificate/test:test",
        "@fizz//fizz/backend/openssl/crypto/aead/test:evpciphers",
        "@fizz//fizz/backend/openssl/crypto/exchange/test:eckey",
        "@fizz//fizz/backend/openssl/crypto/signature/test:ec",
        "@fizz//fizz/backend/openssl/crypto/signature/test:ed",
        "@fizz//fizz/backend/openssl/crypto/signature/test:peer_cert_verify",
        "@fizz//fizz/backend/openssl/crypto/signature/test:rsa_pss",
        "@fizz//fizz/backend/openssl/crypto/test:hmac_test",
        "@fizz//fizz/backend/openssl/crypto/test:key_utils",
        "@fizz//fizz/client/test:async_fizz_client_test",
        "@fizz//fizz/client/test:cert_manager_test",
        "@fizz//fizz/client/test:client_context_test",
        "@fizz//fizz/client/test:client_protocol_test",
        "@fizz//fizz/client/test:fizz_client_test",
        "@fizz//fizz/client/test:multi_client_extensions_test",
        "@fizz//fizz/client/test:psk_serialization_test",
        "@fizz//fizz/client/test:synchronized_lru_psk_cache_test",
        "@fizz//fizz/compression/test:brotli_certificate_compressor_test",
        "@fizz//fizz/compression/test:cert_decompression_manager_test",
        "@fizz//fizz/compression/test:zlib_certificate_compressor_test",
        "@fizz//fizz/compression/test:zstd_certificate_compressor_test",
        "@fizz//fizz/crypto/aead/test:util_test",
        "@fizz//fizz/crypto/exchange/test:HybridExchange",
        "@fizz//fizz/crypto/exchange/test:x25519",
        "@fizz//fizz/crypto/hpke/test:context_test",
        "@fizz//fizz/crypto/hpke/test:dhkem_test",
        "@fizz//fizz/crypto/hpke/test:hpke_test",
        "@fizz//fizz/crypto/test:hkdf_tests",
        "@fizz//fizz/crypto/test:key_derivation",
        "@fizz//fizz/crypto/test:random_generator_test",
        "@fizz//fizz/crypto/test:utils_test",
        "@fizz//fizz/experimental/batcher/test:batcher_test",
        "@fizz//fizz/experimental/client/test:batch_signature_peer_cert_test",
        "@fizz//fizz/experimental/crypto/test:batch_signature_test",
        "@fizz//fizz/experimental/crypto/test:merkle_tree_test",
        "@fizz//fizz/experimental/ktls/test:async_fizz_base_ktls_test",
        "@fizz//fizz/experimental/ktls/test:async_ktls_rx_socket_test",
        "@fizz//fizz/experimental/ktls/test:async_ktls_socket_test",
        "@fizz//fizz/experimental/ktls/test:ktls_test",
        "@fizz//fizz/experimental/protocol/test:batch_signature_types_test",
        "@fizz//fizz/experimental/psp/test",
        "@fizz//fizz/experimental/server/test:batch_signature_async_self_cert_test",
        "@fizz//fizz/extensions/clientpadding/test:padding_client_extension_test",
        "@fizz//fizz/extensions/delegatedcred/test:delegated_credential_cert_manager_test",
        "@fizz//fizz/extensions/delegatedcred/test:delegated_credential_client_cert_manager_test",
        "@fizz//fizz/extensions/delegatedcred/test:delegated_credential_factory_test",
        "@fizz//fizz/extensions/delegatedcred/test:delegated_credential_types_test",
        "@fizz//fizz/extensions/delegatedcred/test:delegated_credential_utils_test",
        "@fizz//fizz/extensions/delegatedcred/test:peer_delegated_credential_test",
        "@fizz//fizz/extensions/delegatedcred/test:self_delegated_credential_test",
        "@fizz//fizz/extensions/delegatedcred/test:serialization_test",
        "@fizz//fizz/extensions/exportedauth/test:exported_authenticator_test",
        "@fizz//fizz/extensions/tokenbinding/test:token_binding_client_extension_test",
        "@fizz//fizz/extensions/tokenbinding/test:token_binding_constructor_test",
        "@fizz//fizz/extensions/tokenbinding/test:token_binding_server_extension_test",
        "@fizz//fizz/extensions/tokenbinding/test:token_binding_test",
        "@fizz//fizz/extensions/tokenbinding/test:validator_test",
        "@fizz//fizz/protocol/ech/test:decrypter_test",
        "@fizz//fizz/protocol/ech/test:ech_test",
        "@fizz//fizz/protocol/ech/test:encryption_test",
        "@fizz//fizz/protocol/ech/test:grease_ech_test",
        "@fizz//fizz/protocol/test:cert_test",
        "@fizz//fizz/protocol/test:cert_verifier",
        "@fizz//fizz/protocol/test:certificate_verifier_test",
        "@fizz//fizz/protocol/test:exporter_test",
        "@fizz//fizz/protocol/test:fizz_base_test",
        "@fizz//fizz/protocol/test:handshake_context_test",
        "@fizz//fizz/protocol/test:key_derivation",
        "@fizz//fizz/protocol/test:multi_backend_factory_test",
        "@fizz//fizz/record/test:buf_and_padding_policy_test",
        "@fizz//fizz/record/test:encrypted_record_test",
        "@fizz//fizz/record/test:extensions_test",
        "@fizz//fizz/record/test:handshake_types_test",
        "@fizz//fizz/record/test:plaintext_record_test",
        "@fizz//fizz/record/test:record_test",
        "@fizz//fizz/record/test:types_test",
        "@fizz//fizz/server/test:aead_cookie_cipher_test",
        "@fizz//fizz/server/test:aead_ticket_cipher_test",
        "@fizz//fizz/server/test:aead_token_cipher_test",
        "@fizz//fizz/server/test:async_fizz_server_test",
        "@fizz//fizz/server/test:cert_manager_test",
        "@fizz//fizz/server/test:cookie_cipher_test",
        "@fizz//fizz/server/test:dual_ticket_cipher_test",
        "@fizz//fizz/server/test:fizz_server_test",
        "@fizz//fizz/server/test:multi_server_extensions_test",
        "@fizz//fizz/server/test:negotiator_test",
        "@fizz//fizz/server/test:server_protocol_test",
        "@fizz//fizz/server/test:sliding_bloom_replay_cache_test",
        "@fizz//fizz/server/test:ticket_codec_test",
        "@fizz//fizz/server/test:ticket_policy_test",
        "@fizz//fizz/test:async_fizz_base_test",
        "@fizz//fizz/test:handshake_test",
        "@fizz//fizz/util/test:fizz_util_test",
        "@fizz//fizz/util/test:key_log_writer_test",
        "@fizz//fizz/util/test:variant_test",
    ],
)
