load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test",
    srcs = ["main.cpp"],
    deps = [
        "@folly//folly/io:iobuf",
        "@wangle//wangle/bootstrap:server_bootstrap",
        "@wangle//wangle/channel:pipeline",
    ],
)

test_suite(
    name = "tests",
    tests = [
        #"@wangle//wangle/acceptor/test:AcceptorTest",
        "@wangle//wangle/acceptor/test:ConnectionManagerTest",
        "@wangle//wangle/acceptor/test:EvbHandshakeHelperTest",
        "@wangle//wangle/acceptor/test:LoadShedConfigurationTest",
        "@wangle//wangle/acceptor/test:PeekingAcceptorHandshakeHelperTest",
        "@wangle//wangle/acceptor/test:SecurityProtocolContextManagerTest",
        "@wangle//wangle/acceptor/test:SharedSSLContextManagerTest",
        "@wangle//wangle/acceptor/test:SocketPeekerTest",
        "@wangle//wangle/bootstrap/test:AcceptRoutingHandlerTest",
        "@wangle//wangle/bootstrap/test:BootstrapTest",
        "@wangle//wangle/channel/broadcast/test:BroadcastHandlerTest",
        "@wangle//wangle/channel/broadcast/test:BroadcastPoolTest",
        "@wangle//wangle/channel/broadcast/test:ObservingClientPipelineTest",
        "@wangle//wangle/channel/broadcast/test:ObservingHandlerTest",
        "@wangle//wangle/channel/test:AsyncSocketHandlerTest",
        "@wangle//wangle/channel/test:FileRegionTest",
        "@wangle//wangle/channel/test:OutputBufferingHandlerTest",
        "@wangle//wangle/channel/test:PipelineTest",
        "@wangle//wangle/codec/test:CodecTest",
        "@wangle//wangle/service/test:ServiceTest",
        "@wangle//wangle/ssl/test:SSLCacheTest",
        "@wangle//wangle/ssl/test:SSLContextManagerTest",
        "@wangle//wangle/ssl/test:SSLSessionCacheManagerTest",
        "@wangle//wangle/ssl/test:TLSCredProcessorTest",
        "@wangle//wangle/ssl/test:TLSInMemoryTicketProcessorTest",
        "@wangle//wangle/ssl/test:TLSTicketKeyManagerTest",
        "@wangle//wangle/util/test:FilePollerTest",
        "@wangle//wangle/util/test:MultiFilePollerTest",
    ],
)
