load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test",
    srcs = ["main.cpp"],
    deps = [
        "@folly//folly/io:iobuf",
        "@wangle//wangle/bootstrap:server_bootstrap",
        "@wangle//wangle/channel:pipeline",
    ],
)

test_suite(
    name = "tests",
    tests = [
        "@wangle//wangle:AsyncSocketHandlerTest",
        "@wangle//wangle:BootstrapTest",
        "@wangle//wangle:BroadcastHandlerTest",
        "@wangle//wangle:BroadcastPoolTest",
        "@wangle//wangle:CodecTest",
        "@wangle//wangle:ConnectionManagerTest",
        "@wangle//wangle:FilePollerTest",
        "@wangle//wangle:LoadShedConfigurationTest",
        "@wangle//wangle:ObservingHandlerTest",
        "@wangle//wangle:OutputBufferingHandlerTest",
        "@wangle//wangle:PeekingAcceptorHandshakeHelperTest",
        "@wangle//wangle:PipelineTest",
        "@wangle//wangle:SSLContextManagerTest",
        "@wangle//wangle:TLSCredProcessorTest",
        "@wangle//wangle:TLSInMemoryTicketProcessorTest",
    ],
)
