load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test",
    srcs = ["main.cpp"],
    deps = ["@proxygen//proxygen:httpserver"],
)

test_suite(
    name = "tests",
    tests = [
        "@proxygen//proxygen/httpserver/filters/tests:HTTPServerFilterTests",
        #"@proxygen//proxygen/httpserver/samples/echo/test:EchoHandlerTests",
        #"@proxygen//proxygen/httpserver/samples/hq/devious/test:DeviousBatonTests",
        #"@proxygen//proxygen/httpserver/samples/hq/test:HQFizzContextTests",
        "@proxygen//proxygen/httpserver/tests:HTTPServerTests",
        "@proxygen//proxygen/lib/dns/test:DNSTests",
        "@proxygen//proxygen/lib/http/codec/compress/test:HPACKTests",
        "@proxygen//proxygen/lib/http/codec/test:BinaryCodecTests",
        "@proxygen//proxygen/lib/http/codec/test:CodecTests",
        "@proxygen//proxygen/lib/http/codec/test:HQCodecTests",
        "@proxygen//proxygen/lib/http/codec/test:HQFramerTests",
        "@proxygen//proxygen/lib/http/codec/webtransport/test:WebTransportTests",
        "@proxygen//proxygen/lib/http/connpool/test:ConnpoolTests",
        "@proxygen//proxygen/lib/http/coro/client/test:CoroDNSResolverTests",
        "@proxygen//proxygen/lib/http/coro/client/test:HTTPClientTests",
        "@proxygen//proxygen/lib/http/coro/util/test:AwaitableKeepAliveTest",
        "@proxygen//proxygen/lib/http/coro/util/test:CancellableBatonTest",
        "@proxygen//proxygen/lib/http/coro/util/test:DetachableExecutorTest",
        "@proxygen//proxygen/lib/http/coro/util/test:TimedBatonTest",
        "@proxygen//proxygen/lib/http/experimental/test:RFC1867Test",
        "@proxygen//proxygen/lib/http/session/test:HQSessionTests",
        "@proxygen//proxygen/lib/http/session/test:SessionTests",
        "@proxygen//proxygen/lib/http/structuredheaders/test:StructuredHeadersTests",
        "@proxygen//proxygen/lib/http/test:LibHTTPTests",
        "@proxygen//proxygen/lib/http/webtransport/test:QuicWebTransportTest",
        "@proxygen//proxygen/lib/http/webtransport/test:WebTransportAPITest",
        "@proxygen//proxygen/lib/http/webtransport/test:WtStreamManagerTest",
        "@proxygen//proxygen/lib/http/webtransport/test:WtUtilsTest",
        "@proxygen//proxygen/lib/sampling/test:SamplingTest",
        "@proxygen//proxygen/lib/services/test:AcceptorTest",
        "@proxygen//proxygen/lib/services/test:RequestWorkerThreadTest",
        "@proxygen//proxygen/lib/stats/test:BaseStatsTest",
        "@proxygen//proxygen/lib/stats/test:PeriodicStatsTest",
        "@proxygen//proxygen/lib/stats/test:ResourceDataTest",
        "@proxygen//proxygen/lib/stats/test:ResourceStatsTest",
        "@proxygen//proxygen/lib/transport/test:TransportTests",
        "@proxygen//proxygen/lib/utils/test:AsyncTimeoutSetTest",
        "@proxygen//proxygen/lib/utils/test:TraceEventTest",
        "@proxygen//proxygen/lib/utils/test:UtilTests",
    ],
)
